index:
    path: /
    controller: App\Controller\DefaultController::index

search:
    path: /search/
    controller: App\Controller\DefaultController::search

model:
    path: /model/{id}
    controller: App\Controller\ModelController::model

add:
    path: /add
    controller: App\Controller\ModelController::addModel

category:
    path: /category/{id}
    controller: App\Controller\CategoryController::category

user:
    path: /user/{id}
    controller: App\Controller\UserController::user

searchget:
    path: api/search/{query}
    controller: App\Controller\DefaultController::searchModel

searchempty:
    path: api/search/
    controller: App\Controller\DefaultController::searchEmpty

userget:
    path: api/userget/{id}
    controller: App\Controller\UserController::getUsers

userModels:
    path: api/userModels/{id}
    controller: App\Controller\UserController::getUserModels

categoryget:
    path: api/categoryget/{id}
    controller: App\Controller\CategoryController::getCategory

featured:
    path: api/featured
    controller: App\Controller\DefaultController::getFeatured

categorylist:
    path: api/categorylist
    controller: App\Controller\CategoryController::getCategoryList

categoryContents:
    path: api/category/{id}
    controller: App\Controller\CategoryController::getCategoryContents

